# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-12 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='customer',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='submission',
            name='revenue',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
