# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-12 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0002_auto_20160812_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='customer',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
