# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-20 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='foo',
            field=models.TextField(blank=True),
        ),
    ]
