# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-21 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0002_submission_foo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='foo',
            new_name='spark_room_id',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='spark_room',
        ),
    ]
