# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-21 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0003_auto_20160821_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='spark_room_id',
            new_name='spark_room',
        ),
    ]
