# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-21 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0004_auto_20160821_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='spark_room_url',
            field=models.TextField(blank=True),
        ),
    ]
